### ISSUE TITLE
Include config 'stylelint-config-airbnb'

### ISSUE THREAD

**Issue by danielvijge** [gilbarbara/codeclimate-stylelint#30] opened 2019-06-19 13:51 UTC
Include the config stylelint-config-airbnb

**Comment by gilbarbara** [comment] 2019-07-12 20:08
hey,
This package seems dead...
I merged your PR but while running the test locally it required an old version of stylelint and I couldn't find the repo to check dependencies.
So I'll remove it.

**Closed by gilbarbara** 2019-07-12 20:08 UTC

**Comment by danielvijge** [comment] 2019-07-13 10:05
Thanks for looking into this.

In the original merge request I didn't include a new package-lock.json, because there were many other merge requests as well, and I thought it might lead to merge conflicts. The old versions are devDependencies only. If a new package-lock.json file is generated with `npm install --package-lock`, it detects that stylelint-config-airbnb only depends on ava and editorconfig-tools.

Would you accept a new merge request that includes package-lock.json?

**Comment by gilbarbara** [comment] 2019-07-13 16:37
The problem is that this package wasn't even merged in Airbnb's repo yet and the last update in the [PR](https://github.com/airbnb/css/pull/56) is from last year.
The published npm version (0.0.0!!) depends on deprecated node.js APIs.

I'm sorry but until the PR is merged and the package is officially maintained I can't add it. Try to send a message in that PR to see if things move.
