### ISSUE TITLE
does codeclimate-stylelint support configs in package.json

### ISSUE THREAD

**Issue by efueger** [gilbarbara/codeclimate-stylelint#38] opened 2020-02-03 15:55 UTC
@gilbarbara - Emily here from Code Climate Support 👋

A customer wrote in reporting they recently migrated over from using stylelint's .stylelintrc file to a "stylelint" property in package.json and now it seems that stylelint is broken.

- does the Stylelint plugin support this setup?

---

- Here's a link to the customer's oss repo: https://github.com/os-js/osjs-panels
- And the plugin's error message: https://codeclimate.com/github/os-js/osjs-panels/pull/27

Let me know if I can provide any additional details. Thanks!

**Comment by andersevenrud** [comment] 2020-02-03 16:12
Also note that I'm using "extends" with a package from npm (containing stylelint rule set).

**Comment by andersevenrud** [comment] 2020-02-03 21:57
I also noted the following on another repo I maintain:

1. A user submitted [this pull request](https://github.com/os-js/osjs-panels/pull/28) and his seems to be OK.
2. I created [this pull request[(https://github.com/os-js/osjs-panels/pull/31) and gets the same error.

Both of those branch HEADs are *after* I changed to the package.json layout + stylelint rule package.

**Comment by gilbarbara** [comment] 2020-02-04 02:45
@efueger @andersevenrud 
I think the problem isn't about the config being in the package.json but with CodeClimate since they don't install packages in their infra.
If you try to load a package that this engine doesn't support, like `@osjs/stylelint-config` it will break,

**Comment by andersevenrud** [comment] 2020-02-04 15:24
@gilbarbara Does this apply to the standard stylelint extensions as well ?

**Comment by andersevenrud** [comment] 2020-02-04 15:35
@efueger You can close this issue. As mentioned in my previous [edited] comment, I'll find an alternate way of running a stylelint check.

**Closed** 2020-02-04 16:12 UTC
